name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  SOURCE_BRANCH: main
  RELEASE_BRANCH: v1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ env.SOURCE_BRANCH }}
          fetch-depth: 0
      - name: Merge
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --no-tags origin "+refs/heads/${RELEASE_BRANCH}:refs/remotes/origin/${RELEASE_BRANCH}"
          git checkout -B "${RELEASE_BRANCH}" "refs/remotes/origin/${RELEASE_BRANCH}"
          git merge "${SOURCE_BRANCH}"
      - name: Push
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          git push origin "${RELEASE_BRANCH}"
