name: Sync Repository

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sync_repo_1:
    name: Sync Repository 1
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: ${{ vars.SYNC_REPO_TARGET_REPO_1 }}
      TARGET_SOURCE_BRANCH: main
      TARGET_RELEASE_BRANCH: v1
    steps:
      - name: Checkout Target
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          path: 'target'
          ref: refs/heads/${{ env.TARGET_SOURCE_BRANCH }}
          ssh-key: ${{ secrets.SYNC_REPO_SSH_KEY_1 }}
          fetch-depth: 0
      - name: Checkout Source
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          path: 'source'
          ref: ${{ github.head_ref }}
      - name: Checkout Source
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3
        with:
          path: 'source'
      - name: Print files and directories
        shell: bash
        run: tree -aI "\.git" "$(pwd)"
      - name: Sync files
        shell: bash
        run: |
          rsync --recursive --exclude=".git/*" "source/" "target"
      - name: Update Repo Name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "pacroy/.github"
          replace: ${{ env.TARGET_REPO }}
          regex: false
          include: 'target/**'
      - name: Create Job Summary
        shell: bash
        working-directory: target
        run: |
          {
            git add .
            synced_files="$(git status --porcelain)"

            if [ -z "${synced_files}" ]; then
              echo ":smile: No change detected. Everything is already in sync."
            else
              echo ":sunglasses: The following changes have been made:"
              echo "\`\`\`console"
              echo "${synced_files}"
              echo "\`\`\`"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Get Commit Message
        id: get_commit_msg
        shell: bash
        working-directory: source
        run: |
          commit_msg=$(git log --no-merges -1 --pretty=format:"%s%n%n%b")
          random_delimiter=$(echo $RANDOM | md5sum | head -c 20)
          {
            echo "commit_msg<<${random_delimiter}"
            echo "${commit_msg}"
            echo
            echo "${random_delimiter}"
          } >> "$GITHUB_OUTPUT"
          echo "::group::Commit message"
          echo "${commit_msg}"
          echo
          echo "::endgroup::"
      - name: Commit to Target
        shell: bash
        working-directory: target
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "${{ steps.get_commit_msg.outputs.commit_msg }}"
          echo "::group::Commit detail"
          git show --pretty=short HEAD
          echo
          echo "::endgroup::"
      - name: Push to Target
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        working-directory: target
        run: |
          git push origin "${TARGET_SOURCE_BRANCH}"
