---
name: "Lint Code Base"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linter:
    if: ${{ github.repository == 'pacroy/.github' }}
    name: "Lint Code Base"
    uses: ./.github/workflows/wf_linter.yml
