---
name: "Lint Code Base"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  linter:
    name: "Lint Code Base"
    uses: ./.github/workflows/wf_linter.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
