---
name: Check Markdown Links

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_mdlink:
    name: Check Markdown Links
    uses: pacroy/.github/.github/workflows/wf_mdlink.yml@v1
